function sources = data_sources()
%This is an example data_sources.m file
%list as many maze and behavior data as desired as long as they are matched
%and provided miniscope video is concatenated accordingly. The format is as
%in below
sources = struct(...
    'maze_1',      '_data/mouse1_trials_ego-left_day5.txt',...
    'maze_2',      '_data/mouse1_trials_ego-left_day6.txt',...
    'behavior_1',  '_data/mouse1_trials_ego-left_day5.mp4',...
    'behavior_2',  '_data/mouse1_trials_ego-left_day6.mp4',...
    'miniscope',   '_data/mouse1_days5-6_sp2_mc_cr_norm_dff-mean.tif',...
    'pca',         '_data/pca_n500.mat',...
    'ic_dir',      'ica001', ...
    'fps', 20);