function centroid_plotter( movie, centroids_mat )
% Plots all centroids on first frame of behavior movie for general inspection
% 
% Input:
%     Behavior movie
%     centroids generated by get_mouse_XY_pos function
%
% Note: Runs sort of slow because you have to access each cell one by one
% via for loop
%     
% 2015-02-27 Fori Wang
    load(centroids_mat)
    figure(1);
    behavior_vid = VideoReader(movie);
    image = read(behavior_vid,1); %grab first frame
    imagesc(image)
    title('Centroit Plotter')
    axis image
    hold on

    for idx = 1:length(centroids)
        this_centroid = centroids{idx};
        plot(this_centroid(1),this_centroid(2),'g*')
        hold on
    end
end